Sonarkube added

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -21,12 +21,12 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - name: Setup Node.js
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4
         with:
-          node-version: '20'
+          node-version: '18'   # 👈 compatible with Sonar
 
       - name: Install dependencies
         working-directory: ${{ matrix.service }}
@@ -36,17 +36,26 @@ jobs:
         working-directory: ${{ matrix.service }}
         run: npm test || echo "No tests found"
 
+
   # -------------------------------
   # 2️⃣ SonarQube Analysis
   # -------------------------------
   sonar:
     name: SonarQube Analysis
     runs-on: ubuntu-latest
-    needs: build-and-test   # 👈 runs after build
+    needs: build-and-test
 
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: '18'
+
+      - name: Install dependencies
+        run: npm install || true
 
       - name: SonarQube Scan
         uses: sonarsource/sonarqube-scan-action@v2
@@ -62,22 +71,20 @@ jobs:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
 
-
-
   # -------------------------------
-  # 2️⃣ Docker Build & Push
+  # 3️⃣ Docker Build & Push
   # -------------------------------
   docker-build-and-push:
     name: Docker Build & Push
     runs-on: ubuntu-latest
-    needs: sonar
+    needs: sonar   # 👈 pipeline stops if sonar fails
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - name: Login to Docker Hub
-        uses: docker/login-action@v2
+        uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
@@ -94,8 +101,9 @@ jobs:
           docker build -t karann24/smartdocs-backend:latest ./backend
           docker push karann24/smartdocs-backend:latest
 
+
   # -------------------------------
-  # 3️⃣ Deploy to EC2
+  # 4️⃣ Deploy to EC2
   # -------------------------------
   deploy:
     name: Deploy to EC2
